DEFINE
TABLE Measures = DATATABLE("static_label", STRING, {{"bonjour"}})		 
		 
//renvoie le code hexadecimal d'une couleur au hasard. La couleur a une luminosité constante de 51% et une dominante rouge, verte ou bleu pour être toujour visible 
MEASURE 'Measures'[color51_alea] = VAR _pos = MOD(SECOND(UTCNOW()),6) + 1 -- RANDBETWEEN(1, 3)
	VAR _ab = RANDBETWEEN(3, 255)
	VAR _an = MOD(_ab, 16)
	VAR _at = IF(_an < 10, FORMAT(_an, "0"), UNICHAR(UNICODE("A") + _an - 10))
	VAR _bn = FLOOR(DIVIDE(_ab, 16), 1)
	VAR _bt = IF(_bn < 10, FORMAT(_bn, "0"), UNICHAR(UNICODE("A") + _bn - 10))
RETURN "#" 
	& SWITCH(_pos, 1, "FF03", 2, "03FF", 3, "FF", 4, "03") 
	& _at & _bt 
	& SWITCH(_pos, 3, "03", 4, "FF", 5, "FF03", 6, "03FF")

//renvoi une valeur héxadécimale entre 0 et F (15)
MEASURE 'Measures'[hexa_alea] = VAR _an = RANDBETWEEN(0, 15)
RETURN IF(_an < 10, FORMAT(_an, "0"), UNICHAR(UNICODE("A") + _an - 10))

//renvoi une couleur complètement aléatoire
//la mesure [hexa_alea] doit être appelé dans un CALCULATE avec une table et enregistrée dans une variable pour forcer plusieurs évaluations successives et ainsi obtenir des valeurs diférentes.
MEASURE 'Measures'[color_alea] = VAR _a = [hexa_alea]
VAR _b = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) // EVALUATEANDLOG([hexa_alea])
VAR _c = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) 
VAR _d = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) 
VAR _e = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) 
VAR _f = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) 
VAR _g = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) 
VAR _h = CALCULATE([hexa_alea], GENERATESERIES(0, 0, 1)) 
RETURN "#" & _a &_b & _c & _d & _e & _f

MEASURE 'Measures'[seconds_alea] = RANDBETWEEN(150, 500)

//renvoi une duréée en secondes au format date/time
//à mettre au format "hh:MM:ss" dans le paramétrage de la mesure
MEASURE 'Measures'[seconds_to_time] = VAR _t = 2395-- [seconds_alea] 
RETURN  TIME(0,0,[seconds_alea])

//renvoi une durée en secondes en un texte au format "hh:mm:ss"
MEASURE 'Measures'[seconds_to_time_txt] = VAR _t = 2395-- [seconds_alea] 
VAR _s = MOD(_t, 60)
VAR _m = MOD(FLOOR(_t/60, 1), 60)
VAR _h = FLOOR(_t/3600, 1)
RETURN  FORMAT(_h, "00") & ":" & FORMAT(_m, "00") & ":" & FORMAT(_s, "00")

	
EVALUATE ADDCOLUMNS(TOPN(1, Measures)
	, "color51_alea", [color51_alea]
	, "hexa_alea", [hexa_alea]
	, "color_alea", [color_alea]
	, "seconds_alea", [seconds_alea]
	, "seconds_to_time", [seconds_to_time]
	, "seconds_to_time2", [seconds_to_time_txt]
)